"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "ar" | "hi" | "ur";

export const languages: Record<Language, { name: string; nativeName: string; dir: "ltr" | "rtl" }> = {
  en: { name: "English", nativeName: "English", dir: "ltr" },
  ar: { name: "Arabic", nativeName: "العربية", dir: "rtl" },
  hi: { name: "Hindi", nativeName: "हिन्दी", dir: "ltr" },
  ur: { name: "Urdu", nativeName: "اردو", dir: "rtl" },
};

export const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.products": "Products",
    "nav.brands": "Brands",
    "nav.manufacturers": "Manufacturers",
    "nav.suppliers": "Suppliers",
    "nav.agents": "Global Suppliers",
    "nav.certifications": "Certifications",
    "nav.specMatcher": "AI Spec Matcher",
    "nav.submittals": "Submittals",
    "nav.search": "Search",
    "nav.signIn": "Sign In",
    "nav.createAccount": "Create Account",
    "hero.title": "AI Spec Matcher",
    "hero.subtitle": "Paste specs. Get compliant products. Instantly.",
    "hero.poweredBy": "Built from Dubai to the world",
    "hero.tryNow": "Try it now",
    "hero.learnMore": "Learn more",
    "hero.sampleSpec": "Sample Specification",
    "hero.matchingProducts": "matching products",
    "hero.ahriVerified": "AHRI verified",
    "hero.localSuppliers": "Local suppliers available",
    "brands.title": "Brand Directory",
    "brands.subtitle": "500+ verified MEP brands. Local supplier networks.",
    "brands.browseAll": "Browse all",
    "brands.listBrand": "List your brand",
    "brands.globalBrands": "Global Brands",
    "brands.verifiedBrands": "Verified brands",
    "brands.products": "Products",
    "brands.fullSpecs": "With full specifications",
    "brands.localSuppliers": "Local Suppliers",
    "brands.acrossGCC": "Across GCC region",
    "certifications.badge": "Compliance Verification",
    "certifications.title": "Real-time certification checks.",
    "certifications.subtitle": "AHRI. UL. FM Global. Eurovent. Verified from official sources.",
    "certifications.verifyNow": "Verify now",
    "products.title": "Products",
    "products.subtitle": "25,000+ MEP products with full specs.",
      "products.browse": "Browse products",
      "agents.title": "Global Suppliers",
      "agents.subtitle": "60 verified suppliers across GCC",
    "agents.find": "Find Suppliers",
    "suppliers.title": "Local Suppliers",
    "suppliers.subtitle": "Find authorized distributors near you.",
    "suppliers.find": "Find suppliers",
    "submittals.title": "Submittal Studio",
    "submittals.subtitle": "Auto-generate compliant submittal packages.",
    "rfq.title": "RFQ System",
    "rfq.subtitle": "Send quotes to multiple suppliers at once.",
    "rfq.create": "Create RFQ",
    "footer.about": "About ProcureSource",
    "footer.copyright": "Copyright (c) 2026 ProcureSource. All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Use",
    "footer.contact": "Contact",
    "common.back": "Back",
    "common.signIn": "Sign In",
    "common.signUp": "Create Account",
    "common.email": "Email",
    "common.password": "Password",
    "common.firstName": "First Name",
    "common.lastName": "Last Name",
    "common.company": "Company",
    "common.role": "Role",
    "common.submit": "Submit",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "login.title": "Sign In",
    "login.subtitle": "Access your ProcureSource account",
    "login.newUser": "New to ProcureSource?",
    "register.title": "Create Account",
    "register.subtitle": "Join the MEP procurement platform",
    "register.hasAccount": "Already have an account?",
    "story.genesis": "Our Genesis",
    "story.title": "Where Precision Meets Purpose.",
    "story.subtitle": "ProcureSource is built from Dubai to the world as a platform for the next generation of MEP procurement.",
    "story.schroeder": "Engineered for GCC procurement teams",
    "story.schroederDesc": "Our core intelligence is built on the robust ProcureSource private launch system, processing millions of compliance parameters with surgical precision in 2026.",
    "story.lycoris": "Built from Dubai to the world",
    "story.lycorisDesc": "Every interaction is crafted so procurement feels precise, trustworthy, and operationally useful.",
    "story.gcc": "GCC Region Compliance",
    "story.gccDesc": "Localized intelligence for the UAE, Saudi Arabia, and Qatar markets, ensuring every product matches specific regional certifications.",
    "story.standard": "The 2026 Standard for MEP Selection.",
    "story.certifiedAccuracy": "Certified Accuracy",
    "story.instantMatching": "Instant Matching",
    "story.fullSubmittal": "Full Submittal Suite",
  },
  ar: {
    "nav.home": "الرئيسية",
    "nav.products": "المنتجات",
    "nav.brands": "العلامات التجارية",
    "nav.manufacturers": "المصنعون",
    "nav.suppliers": "الموردون",
    "nav.agents": "الوكلاء",
    "nav.certifications": "الشهادات",
    "nav.specMatcher": "مطابق المواصفات AI",
    "nav.submittals": "التقديمات",
    "nav.search": "بحث",
    "nav.signIn": "تسجيل الدخول",
    "nav.createAccount": "إنشاء حساب",
    "hero.title": "مطابق المواصفات AI",
    "hero.subtitle": "الصق المواصفات. احصل على منتجات متوافقة. فوراً.",
    "hero.poweredBy": "Built from Dubai to the world",
    "hero.tryNow": "جربه الآن",
    "hero.learnMore": "اعرف المزيد",
    "hero.sampleSpec": "مواصفات نموذجية",
    "hero.matchingProducts": "منتجات مطابقة",
    "hero.ahriVerified": "معتمد من AHRI",
    "hero.localSuppliers": "موردون محليون متاحون",
    "brands.title": "دليل العلامات التجارية",
    "brands.subtitle": "أكثر من 500 علامة تجارية معتمدة. شبكات موردين محلية.",
    "brands.browseAll": "تصفح الكل",
    "brands.listBrand": "أضف علامتك التجارية",
    "brands.globalBrands": "علامات تجارية عالمية",
    "brands.verifiedBrands": "علامات تجارية معتمدة",
    "brands.products": "منتجات",
    "brands.fullSpecs": "مع مواصفات كاملة",
    "brands.localSuppliers": "موردون محليون",
    "brands.acrossGCC": "في منطقة الخليج",
    "certifications.badge": "التحقق من الامتثال",
    "certifications.title": "فحوصات الشهادات في الوقت الفعلي.",
    "certifications.subtitle": "AHRI. UL. FM Global. Eurovent. تم التحقق من مصادر رسمية.",
    "certifications.verifyNow": "تحقق الآن",
    "products.title": "المنتجات",
    "products.subtitle": "أكثر من 25,000 منتج MEP مع مواصفات كاملة.",
    "products.browse": "تصفح المنتجات",
    "suppliers.title": "الموردون المحليون",
    "suppliers.subtitle": "ابحث عن موزعين معتمدين بالقرب منك.",
    "suppliers.find": "ابحث عن موردين",
    "submittals.title": "استوديو التقديمات",
    "submittals.subtitle": "إنشاء حزم تقديم متوافقة تلقائياً.",
    "rfq.title": "نظام طلب عروض الأسعار",
    "rfq.subtitle": "أرسل عروض أسعار لعدة موردين في وقت واحد.",
    "rfq.create": "إنشاء طلب عرض أسعار",
    "footer.about": "عن ProcureSource",
    "footer.copyright": "Copyright (c) 2026 ProcureSource. All rights reserved.",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الاستخدام",
    "footer.contact": "اتصل بنا",
    "common.back": "رجوع",
    "common.signIn": "تسجيل الدخول",
    "common.signUp": "إنشاء حساب",
    "common.email": "البريد الإلكتروني",
    "common.password": "كلمة المرور",
    "common.firstName": "الاسم الأول",
    "common.lastName": "اسم العائلة",
    "common.company": "الشركة",
    "common.role": "الدور",
    "common.submit": "إرسال",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.loading": "جارٍ التحميل...",
    "common.error": "خطأ",
    "common.success": "نجاح",
    "login.title": "تسجيل الدخول",
    "login.subtitle": "الوصول إلى حسابك في ProcureSource",
    "login.newUser": "جديد على ProcureSource؟",
    "register.title": "إنشاء حساب",
    "register.subtitle": "انضم إلى منصة مشتريات MEP",
    "register.hasAccount": "لديك حساب بالفعل؟",
    "story.genesis": "بدايتنا",
    "story.title": "حيث تلتقي الدقة بالهدف.",
    "story.subtitle": "ProcureSource is built from Dubai to the world as a platform for the next generation of MEP procurement.",
    "story.schroeder": "Engineered for GCC procurement teams",
    "story.schroederDesc": "ذكاؤنا الأساسي مبني على محرك بيانات شرودر القوي، يعالج ملايين معايير الامتثال بدقة جراحية في 2026.",
    "story.lycoris": "Built from Dubai to the world",
    "story.lycorisDesc": "Every interaction is crafted so procurement feels precise, trustworthy, and operationally useful.",
    "story.gcc": "امتثال منطقة الخليج",
    "story.gccDesc": "ذكاء محلي لأسواق الإمارات والسعودية وقطر، مع ضمان مطابقة كل منتج للشهادات الإقليمية.",
    "story.standard": "معيار 2026 لاختيار MEP.",
    "story.certifiedAccuracy": "دقة معتمدة",
    "story.instantMatching": "مطابقة فورية",
    "story.fullSubmittal": "حزمة تقديم كاملة",
  },
  hi: {
    "nav.home": "होम",
    "nav.products": "उत्पाद",
    "nav.brands": "ब्रांड्स",
    "nav.manufacturers": "निर्माता",
    "nav.suppliers": "आपूर्तिकर्ता",
    "nav.agents": "एजेंट",
    "nav.certifications": "प्रमाणपत्र",
    "nav.specMatcher": "AI स्पेक मैचर",
    "nav.submittals": "सबमिटल्स",
    "nav.search": "खोजें",
    "nav.signIn": "साइन इन",
    "nav.createAccount": "खाता बनाएं",
    "hero.title": "AI स्पेक मैचर",
    "hero.subtitle": "स्पेक्स पेस्ट करें। अनुपालित उत्पाद प्राप्त करें। तुरंत।",
    "hero.poweredBy": "Built from Dubai to the world",
    "hero.tryNow": "अभी आज़माएं",
    "hero.learnMore": "और जानें",
    "hero.sampleSpec": "नमूना विनिर्देश",
    "hero.matchingProducts": "मिलान उत्पाद",
    "hero.ahriVerified": "AHRI सत्यापित",
    "hero.localSuppliers": "स्थानीय आपूर्तिकर्ता उपलब्ध",
    "brands.title": "ब्रांड निर्देशिका",
    "brands.subtitle": "500+ सत्यापित MEP ब्रांड। स्थानीय आपूर्तिकर्ता नेटवर्क।",
    "brands.browseAll": "सभी देखें",
    "brands.listBrand": "अपना ब्रांड जोड़ें",
    "brands.globalBrands": "वैश्विक ब्रांड",
    "brands.verifiedBrands": "सत्यापित ब्रांड",
    "brands.products": "उत्पाद",
    "brands.fullSpecs": "पूर्ण विनिर्देशों के साथ",
    "brands.localSuppliers": "स्थानीय आपूर्तिकर्ता",
    "brands.acrossGCC": "GCC क्षेत्र में",
    "certifications.badge": "अनुपालन सत्यापन",
    "certifications.title": "रीयल-टाइम प्रमाणन जांच।",
    "certifications.subtitle": "AHRI. UL. FM Global. Eurovent. आधिकारिक स्रोतों से सत्यापित।",
    "certifications.verifyNow": "अभी सत्यापित करें",
    "products.title": "उत्पाद",
    "products.subtitle": "25,000+ MEP उत्पाद पूर्ण स्पेक्स के साथ।",
    "products.browse": "उत्पाद ब्राउज़ करें",
    "suppliers.title": "स्थानीय आपूर्तिकर्ता",
    "suppliers.subtitle": "अपने पास अधिकृत वितरक खोजें।",
    "suppliers.find": "आपूर्तिकर्ता खोजें",
    "submittals.title": "सबमिटल स्टूडियो",
    "submittals.subtitle": "अनुपालित सबमिटल पैकेज स्वतः उत्पन्न करें।",
    "rfq.title": "RFQ सिस्टम",
    "rfq.subtitle": "एक साथ कई आपूर्तिकर्ताओं को कोट भेजें।",
    "rfq.create": "RFQ बनाएं",
    "footer.about": "ProcureSource के बारे में",
    "footer.copyright": "Copyright (c) 2026 ProcureSource. All rights reserved.",
    "footer.privacy": "गोपनीयता नीति",
    "footer.terms": "उपयोग की शर्तें",
    "footer.contact": "संपर्क",
    "common.back": "वापस",
    "common.signIn": "साइन इन",
    "common.signUp": "खाता बनाएं",
    "common.email": "ईमेल",
    "common.password": "पासवर्ड",
    "common.firstName": "पहला नाम",
    "common.lastName": "उपनाम",
    "common.company": "कंपनी",
    "common.role": "भूमिका",
    "common.submit": "जमा करें",
    "common.cancel": "रद्द करें",
    "common.save": "सहेजें",
    "common.loading": "लोड हो रहा है...",
    "common.error": "त्रुटि",
    "common.success": "सफलता",
    "login.title": "साइन इन",
    "login.subtitle": "अपने ProcureSource खाते तक पहुंचें",
    "login.newUser": "ProcureSource में नए हैं?",
    "register.title": "खाता बनाएं",
    "register.subtitle": "MEP प्रोक्योरमेंट प्लेटफॉर्म से जुड़ें",
    "register.hasAccount": "पहले से खाता है?",
    "story.genesis": "हमारी शुरुआत",
    "story.title": "जहां सटीकता उद्देश्य से मिलती है।",
    "story.subtitle": "ProcureSource is built from Dubai to the world as a platform for the next generation of MEP procurement.",
    "story.schroeder": "Engineered for GCC procurement teams",
    "story.schroederDesc": "हमारी मुख्य बुद्धिमत्ता मजबूत श्रोएडर डेटा इंजन पर बनी है, 2026 में सर्जिकल सटीकता के साथ लाखों अनुपालन मापदंडों को संसाधित करती है।",
    "story.lycoris": "Built from Dubai to the world",
    "story.lycorisDesc": "Every interaction is crafted so procurement feels precise, trustworthy, and operationally useful.",
    "story.gcc": "GCC क्षेत्र अनुपालन",
    "story.gccDesc": "UAE, सऊदी अरब और कतर बाजारों के लिए स्थानीयकृत बुद्धिमत्ता, यह सुनिश्चित करते हुए कि हर उत्पाद विशिष्ट क्षेत्रीय प्रमाणपत्रों से मेल खाता है।",
    "story.standard": "MEP चयन के लिए 2026 मानक।",
    "story.certifiedAccuracy": "प्रमाणित सटीकता",
    "story.instantMatching": "तत्काल मिलान",
    "story.fullSubmittal": "पूर्ण सबमिटल सूट",
  },
  ur: {
    "nav.home": "ہوم",
    "nav.products": "مصنوعات",
    "nav.brands": "برانڈز",
    "nav.manufacturers": "مینوفیکچررز",
    "nav.suppliers": "سپلائرز",
    "nav.agents": "ایجنٹس",
    "nav.certifications": "سرٹیفیکیشن",
    "nav.specMatcher": "AI سپیک میچر",
    "nav.submittals": "سبمٹلز",
    "nav.search": "تلاش",
    "nav.signIn": "سائن ان",
    "nav.createAccount": "اکاؤنٹ بنائیں",
    "hero.title": "AI سپیک میچر",
    "hero.subtitle": "سپیکس پیسٹ کریں۔ مطابق مصنوعات حاصل کریں۔ فوری۔",
    "hero.poweredBy": "Built from Dubai to the world",
    "hero.tryNow": "ابھی آزمائیں",
    "hero.learnMore": "مزید جانیں",
    "hero.sampleSpec": "نمونہ تفصیلات",
    "hero.matchingProducts": "ملتی مصنوعات",
    "hero.ahriVerified": "AHRI تصدیق شدہ",
    "hero.localSuppliers": "مقامی سپلائرز دستیاب",
    "brands.title": "برانڈز کی ڈائریکٹری",
    "brands.subtitle": "500+ تصدیق شدہ MEP برانڈز۔ مقامی سپلائر نیٹ ورکس۔",
    "brands.browseAll": "سب دیکھیں",
    "brands.listBrand": "اپنا برانڈ شامل کریں",
    "brands.globalBrands": "عالمی برانڈز",
    "brands.verifiedBrands": "تصدیق شدہ برانڈز",
    "brands.products": "مصنوعات",
    "brands.fullSpecs": "مکمل تفصیلات کے ساتھ",
    "brands.localSuppliers": "مقامی سپلائرز",
    "brands.acrossGCC": "GCC خطے میں",
    "certifications.badge": "تعمیل کی تصدیق",
    "certifications.title": "ریئل ٹائم سرٹیفکیشن چیک۔",
    "certifications.subtitle": "AHRI. UL. FM Global. Eurovent. سرکاری ذرائع سے تصدیق شدہ۔",
    "certifications.verifyNow": "ابھی تصدیق کریں",
    "products.title": "مصنوعات",
    "products.subtitle": "25,000+ MEP مصنوعات مکمل سپیکس کے ساتھ۔",
    "products.browse": "مصنوعات براؤز کریں",
    "suppliers.title": "مقامی سپلائرز",
    "suppliers.subtitle": "اپنے قریب مجاز تقسیم کار تلاش کریں۔",
    "suppliers.find": "سپلائرز تلاش کریں",
    "submittals.title": "سبمٹل اسٹوڈیو",
    "submittals.subtitle": "مطابق سبمٹل پیکجز خود بخود بنائیں۔",
    "rfq.title": "RFQ سسٹم",
    "rfq.subtitle": "ایک ساتھ متعدد سپلائرز کو قیمتیں بھیجیں۔",
    "rfq.create": "RFQ بنائیں",
    "footer.about": "ProcureSource کے بارے میں",
    "footer.copyright": "Copyright (c) 2026 ProcureSource. All rights reserved.",
    "footer.privacy": "پرائیویسی پالیسی",
    "footer.terms": "استعمال کی شرائط",
    "footer.contact": "رابطہ",
    "common.back": "واپس",
    "common.signIn": "سائن ان",
    "common.signUp": "اکاؤنٹ بنائیں",
    "common.email": "ای میل",
    "common.password": "پاس ورڈ",
    "common.firstName": "پہلا نام",
    "common.lastName": "آخری نام",
    "common.company": "کمپنی",
    "common.role": "کردار",
    "common.submit": "جمع کریں",
    "common.cancel": "منسوخ",
    "common.save": "محفوظ کریں",
    "common.loading": "لوڈ ہو رہا ہے...",
    "common.error": "خرابی",
    "common.success": "کامیابی",
    "login.title": "سائن ان",
    "login.subtitle": "اپنے ProcureSource اکاؤنٹ تک رسائی حاصل کریں",
    "login.newUser": "ProcureSource پر نئے ہیں؟",
    "register.title": "اکاؤنٹ بنائیں",
    "register.subtitle": "MEP پروکیورمنٹ پلیٹ فارم میں شامل ہوں",
    "register.hasAccount": "پہلے سے اکاؤنٹ ہے؟",
    "story.genesis": "ہماری ابتدا",
    "story.title": "جہاں درستگی مقصد سے ملتی ہے۔",
    "story.subtitle": "ProcureSource is built from Dubai to the world as a platform for the next generation of MEP procurement.",
    "story.schroeder": "Engineered for GCC procurement teams",
    "story.schroederDesc": "ہماری بنیادی ذہانت مضبوط شروڈر ڈیٹا انجن پر بنی ہے، 2026 میں سرجیکل درستگی کے ساتھ لاکھوں تعمیل پیرامیٹرز پر کارروائی کرتی ہے۔",
    "story.lycoris": "Built from Dubai to the world",
    "story.lycorisDesc": "Every interaction is crafted so procurement feels precise, trustworthy, and operationally useful.",
    "story.gcc": "GCC خطے کی تعمیل",
    "story.gccDesc": "UAE، سعودی عرب اور قطر کی مارکیٹوں کے لیے مقامی ذہانت، اس بات کو یقینی بناتے ہوئے کہ ہر مصنوعات مخصوص علاقائی سرٹیفکیشن سے میل کھاتی ہے۔",
    "story.standard": "MEP انتخاب کے لیے 2026 معیار۔",
    "story.certifiedAccuracy": "تصدیق شدہ درستگی",
    "story.instantMatching": "فوری مماثلت",
    "story.fullSubmittal": "مکمل سبمٹل سوٹ",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("procuresource_language") as Language;
    if (saved && languages[saved]) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("procuresource_language", lang);
    document.documentElement.dir = languages[lang].dir;
    document.documentElement.lang = lang;
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  const dir = languages[language].dir;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
